/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fish/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Identify */
        post: operations["identify_api_v1_fish_identify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fish/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_fish_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/{prediction_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge Card */
        get: operations["knowledge_card_api_v1_predictions__prediction_id__knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_identify_api_v1_fish_identify_post */
        Body_identify_api_v1_fish_identify_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentificationResponse */
        IdentificationResponse: {
            /** Prediction Id */
            prediction_id: string;
            /** Model Version */
            model_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "confident_prediction" | "low_confidence_human_verification_required";
            prediction: components["schemas"]["SpeciesCandidate"];
            /** Top Candidates */
            top_candidates: components["schemas"]["SpeciesCandidate"][];
            /** Threshold */
            threshold: number;
            /**
             * Verification Status
             * @constant
             */
            verification_status: "pending";
        };
        /** KnowledgeCard */
        KnowledgeCard: {
            /** Common Name */
            common_name: string;
            /** Scientific Name */
            scientific_name: string | null;
            /** Taxonomy Status */
            taxonomy_status: string;
            /** Physical Characteristics */
            physical_characteristics: string | null;
            /** Taste */
            taste: string | null;
            /** Texture */
            texture: string | null;
            /** Processing Methods */
            processing_methods: string[];
            /** Commercial Uses */
            commercial_uses: string[];
            /** Similar Or Substitute Species */
            similar_or_substitute_species: string[];
            /** Potential Buyer Segments */
            potential_buyer_segments: string[];
            /** Limitations */
            limitations: string[];
            /** Sources */
            sources: components["schemas"]["SourceMetadata"][];
        };
        /** KnowledgeResponse */
        KnowledgeResponse: {
            /** Prediction Id */
            prediction_id: string;
            /** Species Id */
            species_id: string;
            card: components["schemas"]["KnowledgeCard"];
        };
        /**
         * SourceMetadata
         * @description Server-side enrichment of a generated citation. Never trusted from
         *     generated text: title/url/publisher/type/review all come from the
         *     retrieved verified source row.
         */
        SourceMetadata: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Url */
            url: string;
            /** Publisher */
            publisher: string;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Verification Status
             * @constant
             */
            verification_status: "verified";
        };
        /** SpeciesCandidate */
        SpeciesCandidate: {
            /** Species Id */
            species_id: string;
            /** Normalized Label */
            normalized_label: string;
            /** Confidence */
            confidence: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationResponse */
        VerificationResponse: {
            /** Prediction Id */
            prediction_id: string;
            /** Predicted Species Id */
            predicted_species_id: string;
            /** Verified Species Id */
            verified_species_id: string;
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "confirmed" | "corrected";
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Prediction Id */
            prediction_id: string;
            /** Verified Species Id */
            verified_species_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    identify_api_v1_fish_identify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_identify_api_v1_fish_identify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_fish_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_card_api_v1_predictions__prediction_id__knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prediction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
