import { SpeciesArt } from '@/components/fish/species-art'
import { kilograms, rupiahPerKg } from '@/lib/format'
import { landingPointName } from '@/lib/landing-points'
import { resolveSpecies } from '@/lib/species'
import { discoverUrl } from '@/lib/qr'
import type { components } from '@/lib/api/schema'

type Lot = components['schemas']['LotResponse']

/** The class the print stylesheet isolates. See `@media print` in globals.css. */
export const PRINT_CARD_CLASS = 'qr-print-card'

/**
 * The physical Fishora card, at the 3:4 ratio it prints at.
 *
 * One fixed shape on every viewport: the operator is holding up the thing a
 * buyer will be handed, so a card that reflows between phone and desktop is
 * showing them something they will not receive. Height is capped against both
 * the viewport height and its width, so the ratio survives a short window and
 * a narrow one.
 */
export function QrCard({ lot }: { lot: Lot }) {
  const label = lot.species_id.replace('species_', '')
  const species = resolveSpecies(label)
  const url = discoverUrl(lot.public_slug)

  return (
    <article
      className={`${PRINT_CARD_CLASS} flex aspect-[3/4] h-[min(64dvh,calc(84vw*4/3))] flex-col overflow-hidden rounded-[var(--radius-card)] bg-surface`}
    >
      {/* Top half: what the fish actually looks like. */}
      <div className="relative h-1/2 shrink-0">
        <SpeciesArt
          label={label}
          className="absolute inset-0"
          sizes="(max-width: 640px) 84vw, 28rem"
          showName={false}
        />
      </div>

      {/* Bottom half: what is being sold, and the codes that carry it onward. */}
      <div className="flex min-h-0 flex-1 gap-3 p-4">
        <div className="flex min-w-0 flex-1 flex-col">
          <h3 className="text-h3 text-ink">{species.commonName}</h3>
          {species.scientificName && (
            <p className="text-body-sm text-ink-muted italic leading-[1.12]">
              {species.scientificName}
            </p>
          )}

          <dl className="mt-auto flex flex-col gap-0.5">
            <Row label="Volume" value={kilograms(Number(lot.quantity_kg))} />
            <Row label="Ukuran" value={lot.size_category} />
            <Row label="Harga awal" value={rupiahPerKg(Number(lot.starting_price_per_kg))} />
            <Row label="Pendaratan" value={landingPointName(lot.landing_point_id)} />
            {lot.seller_fisher_group && <Row label="Nelayan" value={lot.seller_fisher_group} />}
          </dl>
        </div>

        {/* Bottom right: the fish profile first, because that is what a shopper
            standing at a shelf is scanning. The Fishora code sits under it. */}
        <div className="flex shrink-0 flex-col items-end justify-end gap-2">
          <Code
            testId="qr-code-fish"
            src={`/api/qr/${lot.public_slug}`}
            alt={`Kode QR profil ${species.commonName}`}
            caption={species.commonName}
            size="size-24"
          />
          <Code
            testId="qr-code-app"
            src="/api/qr/app"
            alt="Kode QR untuk membuka Fishora"
            caption="Fishora"
            size="size-14"
          />
          <p className="sr-only">{url}</p>
        </div>
      </div>
    </article>
  )
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-baseline justify-between gap-3">
      <dt className="text-body-sm shrink-0 text-ink-muted">{label}</dt>
      <dd className="text-num-sm min-w-0 text-right text-ink">{value}</dd>
    </div>
  )
}

function Code({
  testId,
  src,
  alt,
  caption,
  size,
}: {
  testId: string
  src: string
  alt: string
  caption: string
  size: string
}) {
  return (
    <div data-testid={testId} className="flex flex-col items-center gap-1">
      {/* A plain img, not next/image: these are generated by our own route at a
          size the card fixes, so there is nothing for the optimiser to pick. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={src} alt={alt} className={`${size} rounded-lg bg-white p-1`} />
      <span className="text-[0.625rem] leading-none text-ink-muted">{caption}</span>
    </div>
  )
}
